<?php require __DIR__.'/includes/bootstrap.php';
$niche=current_niche();$cat=(string)get('cat','');$best=(int)get('best',0);$sale=(int)get('sale',0);$sort=(string)get('sort','recent');$q='';$params=[$niche];
$sql="SELECT p.*,c.name category_name,c.slug category_slug,(SELECT image FROM product_images WHERE product_id=p.id ORDER BY sort_order,id LIMIT 1) AS image FROM products p JOIN categories c ON c.id=p.category_id WHERE p.status=1 AND c.type=?";
if($cat && !in_array($cat,['best','sale'],true)){$sql.=' AND c.slug=?';$params[]=$cat;}
if($cat==='best')$best=1;if($cat==='sale')$sale=1;if($best)$sql.=' AND p.is_best_seller=1';if($sale)$sql.=' AND p.compare_price IS NOT NULL';
if($sort==='price-low')$sql.=' ORDER BY p.price ASC';elseif($sort==='price-high')$sql.=' ORDER BY p.price DESC';elseif($sort==='rating')$sql.=' ORDER BY p.rating DESC';else $sql.=' ORDER BY p.featured DESC,p.created_at DESC';
$st=db()->prepare($sql);$st->execute($params);$products=$st->fetchAll();$cats=db()->prepare('SELECT * FROM categories WHERE type=? ORDER BY sort_order');$cats->execute([$niche]);$categories=$cats->fetchAll();$title='Category Listing';require __DIR__.'/includes/header.php';
?>
<div class="max-w-[1480px] mx-auto px-3 sm:px-5 py-8"><section class="flex-1"><div class="flex flex-col md:flex-row items-start md:items-end justify-between gap-4 mb-5"><div><div class="text-xs tracking-[.2em] text-[var(--accent-soft)] font-black"><?=ucfirst($niche)?></div><h1 class="text-3xl font-black mt-1"><?=e($cat?str_replace('-',' ',$cat):'All Products')?></h1><div class="text-sm text-[var(--muted)] mt-1"><?=count($products)?> products</div></div><div class="w-full md:w-auto"><select onchange="window.location='?niche=<?=$niche?>&cat=<?=$cat?>&sort='+this.value" class="w-full border line rounded-xl px-4 py-2.5 bg-[var(--surface-2)] text-[var(--text)]"><option value="recent" <?=$sort==='recent'?'selected':''?>>Newest</option><option value="price-low" <?=$sort==='price-low'?'selected':''?>>Price: Low to High</option><option value="price-high" <?=$sort==='price-high'?'selected':''?>>Price: High to Low</option><option value="rating" <?=$sort==='rating'?'selected':''?>>Highest Rated</option></select></div></div><div class="grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-4"><?php if(!$products): ?><div class="col-span-full py-20 text-center">No products found.</div><?php else: foreach($products as $p): include __DIR__.'/includes/product_card.php'; endforeach; endif; ?></div></section></div>
<?php require __DIR__.'/includes/footer.php'; ?>
