<?php
$title='Content';require __DIR__.'/inc/header.php';$type=(string)get('type','articles');if(!in_array($type,['gadgets','jersey','fashion','articles','docs','pages'],true))$type='articles';$pdo=db();$message='';
$cats=$pdo->prepare("SELECT id,name FROM categories WHERE type IN (?, 'articles','docs','pages') AND status=1 ORDER BY name");$cats->execute([$type]);$cats=$cats->fetchAll();
$tags=$pdo->prepare("SELECT id,name FROM terms WHERE taxonomy='tag' AND post_type=? AND status=1 ORDER BY name");$tags->execute([$type]);$tags=$tags->fetchAll();
if(is_post()){verify_csrf();$action=(string)post('action','');
 if($action==='save'){ $id=(int)post('id',0);$titleX=trim((string)post('title'));$slug=slugify((string)post('slug',$titleX));$excerpt=trim((string)post('excerpt'));$content=(string)post('content');$status=(string)post('status','draft');$visibility=(string)post('visibility','public');$cat=(int)post('category_id',0)?:null;$seoT=trim((string)post('seo_title'));$seoD=trim((string)post('seo_description'));$seoK=trim((string)post('seo_keywords'));$schema=(string)post('schema_type','Article');$featured=post('featured')?1:0;$cover='';
   if(!empty($_FILES['cover_file']['name'])){try{$u=save_public_upload($_FILES['cover_file'],['jpg','jpeg','png','webp','gif','svg'],12000000,'content');$cover=$u['path'];}catch(Throwable $e){$message=$e->getMessage();}}
   if(!$cover)$cover=(string)post('existing_cover','');
   try{if($id){$pdo->prepare('UPDATE content_posts SET title=?,slug=?,excerpt=?,content=?,status=?,visibility=?,category_id=?,cover_image=?,seo_title=?,seo_description=?,seo_keywords=?,schema_type=?,featured=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND post_type=?')->execute([$titleX,$slug,$excerpt,$content,$status,$visibility,$cat,$cover,$seoT,$seoD,$seoK,$schema,$featured,$id,$type]);$postId=$id;}else{$pdo->prepare('INSERT INTO content_posts(post_type,title,slug,excerpt,content,status,visibility,category_id,cover_image,seo_title,seo_description,seo_keywords,schema_type,featured,author_id,published_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$type,$titleX,$slug,$excerpt,$content,$status,$visibility,$cat,$cover,$seoT,$seoD,$seoK,$schema,$featured,user()['id']??null,$status==='publish'?date('Y-m-d H:i:s'):null]);$postId=(int)$pdo->lastInsertId();}$pdo->prepare('DELETE FROM post_terms WHERE post_id=?')->execute([$postId]);foreach((array)post('tags',[]) as $tid)$pdo->prepare('INSERT OR IGNORE INTO post_terms(post_id,term_id) VALUES(?,?)')->execute([$postId,(int)$tid]);flash('success',($id?'Updated':'Created').' '.post_type_label($type).'.');redirect('/admin/content.php?type='.$type.'&edit='.$postId.'#editor');}catch(Throwable $e){$message=$e->getMessage();}
 }
 if($action==='bulk'){$ids=array_values(array_filter(array_map('intval',(array)post('ids',[]))));$bulk=(string)post('bulk_action','');if($ids){$ph=implode(',',array_fill(0,count($ids),'?'));
   if($bulk==='delete'){$pdo->prepare("DELETE FROM content_posts WHERE post_type=? AND id IN ($ph)")->execute([$type,...$ids]);flash('success','Selected posts deleted.');}
   elseif(in_array($bulk,['publish','draft','private'],true)){$pdo->prepare("UPDATE content_posts SET status=? WHERE post_type=? AND id IN ($ph)")->execute([$bulk,$type,...$ids]);flash('success','Status updated.');}
   elseif($bulk==='category:clear'){$pdo->prepare("UPDATE content_posts SET category_id=NULL WHERE post_type=? AND id IN ($ph)")->execute([$type,...$ids]);flash('success','Categories removed from selected posts.');}
   elseif(str_starts_with($bulk,'category:assign:')){$cid=(int)substr($bulk,16);$pdo->prepare("UPDATE content_posts SET category_id=? WHERE post_type=? AND id IN ($ph)")->execute([$cid,$type,...$ids]);flash('success','Category assigned.');}
   elseif(str_starts_with($bulk,'tag:add:')){$tid=(int)substr($bulk,8);foreach($ids as $pid)$pdo->prepare('INSERT OR IGNORE INTO post_terms(post_id,term_id) VALUES(?,?)')->execute([$pid,$tid]);flash('success','Tag assigned to selected posts.');}
   elseif(str_starts_with($bulk,'tag:remove:')){$tid=(int)substr($bulk,11);foreach($ids as $pid)$pdo->prepare('DELETE FROM post_terms WHERE post_id=? AND term_id=?')->execute([$pid,$tid]);flash('success','Tag removed from selected posts.');}
   elseif($bulk==='tags:clear'){foreach($ids as $pid)$pdo->prepare('DELETE FROM post_terms WHERE post_id=?')->execute([$pid]);flash('success','All tags removed from selected posts.');}
  }redirect('/admin/content.php?type='.$type);}
}
$editId=(int)get('edit',0);if($editId){redirect('/admin/content-edit.php?type='.$type.'&id='.$editId);} $edit=null;if(false){$st=$pdo->prepare('SELECT * FROM content_posts WHERE id=? AND post_type=?');$st->execute([$editId,$type]);$edit=$st->fetch();}
$form=$edit?:['id'=>0,'title'=>'','slug'=>'','excerpt'=>'','content'=>'','status'=>'draft','visibility'=>'public','category_id'=>'','cover_image'=>'','seo_title'=>'','seo_description'=>'','seo_keywords'=>'','schema_type'=>'Article','featured'=>0];
$posts=$pdo->prepare("SELECT p.*,c.name category_name FROM content_posts p LEFT JOIN categories c ON c.id=p.category_id WHERE p.post_type=? ORDER BY p.id DESC");$posts->execute([$type]);$posts=$posts->fetchAll();
$selectedTags=[];if($edit){$st=$pdo->prepare('SELECT term_id FROM post_terms WHERE post_id=?');$st->execute([$edit['id']]);$selectedTags=array_map('intval',$st->fetchAll(PDO::FETCH_COLUMN));}
?>
<div class="flex flex-col lg:flex-row lg:items-center justify-between gap-3 mb-6"><div><div class="text-xs tracking-[.2em] text-slate-400 font-black">CONTENT TYPE</div><h1 class="text-3xl font-black"><?=e(post_type_label($type))?></h1><div class="text-sm text-slate-500 mt-1">SEO URLs: /<?=e($type)?>/your-slug</div></div><a href="/admin/content-edit.php?type=<?=$type?>&id=0" class="grad600 shine text-white px-4 py-3 rounded-xl font-black">+ New <?=e(post_type_label($type))?></a></div>
<?php if($message):?><div class="mb-4 bg-rose-50 border border-rose-100 text-rose-700 p-3 rounded-xl"><?=e($message)?></div><?php endif;?>
<div class="grid xl:grid-cols-[1fr_560px] gap-6">
<div class="bg-white border rounded-2xl overflow-hidden soft"><form method="post" onsubmit="return confirmBulk()"><div class="p-4 border-b flex flex-col xl:flex-row gap-2"><?=csrf_input()?><input type="hidden" name="action" value="bulk"><input id="contentSearch" oninput="filterRows()" placeholder="Search posts..." class="flex-1 rounded-xl border-slate-200"><select name="bulk_action" class="rounded-xl border-slate-200"><option value="">Bulk action</option><option value="publish">Publish</option><option value="draft">Move to Draft</option><option value="private">Set Private</option><option value="delete">Delete</option><option value="category:clear">Remove Category</option><?php foreach($cats as $c):?><option value="category:assign:<?=$c['id']?>">Assign Category: <?=e($c['name'])?></option><?php endforeach;?><option value="tags:clear">Remove All Tags</option><?php foreach($tags as $t):?><option value="tag:add:<?=$t['id']?>">Add Tag: <?=e($t['name'])?></option><option value="tag:remove:<?=$t['id']?>">Remove Tag: <?=e($t['name'])?></option><?php endforeach;?></select><button class="rounded-xl bg-slate-950 text-white px-4 font-bold">Apply</button></div><div class="overflow-x-auto"><table class="w-full text-sm" id="contentTable"><thead class="bg-slate-50"><tr><th class="p-3"><input type="checkbox" onclick="document.querySelectorAll('.rowcheck').forEach(x=>x.checked=this.checked)"></th><th class="p-3 text-left">Title</th><th class="p-3 text-left">Category</th><th class="p-3 text-left">Status</th><th class="p-3 text-right">Action</th></tr></thead><tbody><?php foreach($posts as $r):?><tr class="border-t content-row"><td class="p-3"><input class="rowcheck" type="checkbox" name="ids[]" value="<?=$r['id']?>"></td><td class="p-3"><div class="font-bold post-title"><?=e($r['title'])?></div><div class="text-xs text-slate-400">/<?=e($type)?>/<?=e($r['slug'])?></div></td><td class="p-3"><?=e($r['category_name']??'—')?></td><td class="p-3"><span class="px-2 py-1 rounded-full text-xs font-bold <?=($r['status']==='publish'?'bg-emerald-100 text-emerald-700':($r['status']==='private'?'bg-purple-100 text-purple-700':'bg-amber-100 text-amber-700'))?>"><?=e($r['status'])?></span></td><td class="p-3 text-right"><a href="/admin/content-edit.php?type=<?=$type?>&id=<?=$r['id']?>" class="text-blue-600 font-black">Edit</a><a href="<?=content_url($type,$r['slug'])?>" target="_blank" class="ml-3 font-bold">View</a></td></tr><?php endforeach;?></tbody></table></div></form></div>
<div id="editor" class="bg-white border rounded-2xl p-5 soft"><div class="font-black text-lg"><?=($form['id']?'Edit':'Create')?> <?=e(post_type_label($type))?></div><form method="post" enctype="multipart/form-data" class="mt-4 space-y-3"><?=csrf_input()?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=e((string)$form['id'])?>"><input required name="title" value="<?=e($form['title'])?>" placeholder="Title" class="w-full rounded-xl border-slate-200"><input name="slug" value="<?=e($form['slug'])?>" placeholder="SEO slug" class="w-full rounded-xl border-slate-200"><textarea name="excerpt" placeholder="Short excerpt" class="w-full rounded-xl border-slate-200 min-h-20"><?=e($form['excerpt'])?></textarea><label class="text-xs font-bold text-slate-500">Content Editor</label><?php require __DIR__.'/rich_editor.php';rich_editor('content',(string)$form['content'],'contentEditor');?>
<div class="grid grid-cols-2 gap-2"><select name="status" class="rounded-xl border-slate-200"><option value="draft" <?=$form['status']==='draft'?'selected':''?>>Draft</option><option value="publish" <?=$form['status']==='publish'?'selected':''?>>Publish</option><option value="private" <?=$form['status']==='private'?'selected':''?>>Private</option></select><select name="visibility" class="rounded-xl border-slate-200"><option value="public" <?=$form['visibility']==='public'?'selected':''?>>Public</option><option value="members" <?=$form['visibility']==='members'?'selected':''?>>Members only</option></select></div><select name="category_id" class="w-full rounded-xl border-slate-200"><option value="">Category</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=$form['category_id']==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select><div><label class="text-xs font-bold text-slate-500">Cover image — choose file</label><input type="file" name="cover_file" accept="image/*" class="mt-1 w-full rounded-xl border p-3 bg-white"><input type="hidden" name="existing_cover" value="<?=e($form['cover_image'])?>"></div><?php if($form['cover_image']):?><img src="<?=e($form['cover_image'])?>" class="w-full h-32 object-cover rounded-xl border"><?php endif;?><div><div class="text-xs font-bold text-slate-500 mb-2">Tags</div><div class="flex flex-wrap gap-2 max-h-32 overflow-auto"><?php foreach($tags as $t):?><label class="flex items-center gap-2 text-xs bg-slate-50 px-3 py-2 rounded-xl"><input type="checkbox" name="tags[]" value="<?=$t['id']?>" <?=in_array((int)$t['id'],$selectedTags,true)?'checked':''?>><?=e($t['name'])?></label><?php endforeach;?></div></div><div class="grid grid-cols-2 gap-2"><input name="seo_title" value="<?=e($form['seo_title'])?>" placeholder="SEO title" class="rounded-xl border-slate-200"><input name="seo_keywords" value="<?=e($form['seo_keywords'])?>" placeholder="SEO keywords" class="rounded-xl border-slate-200"><textarea name="seo_description" placeholder="Meta description" class="rounded-xl border-slate-200 min-h-20 col-span-2"><?=e($form['seo_description'])?></textarea><select name="schema_type" class="rounded-xl border-slate-200 col-span-2"><option <?=($form['schema_type']==='Article'?'selected':'')?>>Article</option><option <?=($form['schema_type']==='WebPage'?'selected':'')?>>WebPage</option><option <?=($form['schema_type']==='TechArticle'?'selected':'')?>>TechArticle</option><option <?=($form['schema_type']==='FAQPage'?'selected':'')?>>FAQPage</option></select></div><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="featured" <?=$form['featured']?'checked':''?>> Featured</label><button class="shine grad600 text-white w-full py-3 rounded-xl font-black">Save <?=e(post_type_label($type))?></button></form></div></div>
<script>function filterRows(){const q=(document.getElementById('contentSearch').value||'').toLowerCase();document.querySelectorAll('.content-row').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none')}function confirmBulk(){const checked=document.querySelectorAll('.rowcheck:checked').length;const a=document.querySelector('select[name=bulk_action]').value;if(!checked){alert('Select at least one post.');return false}if(a==='delete'&& !confirm('Delete selected posts? This cannot be undone.'))return false;return true}</script>
<?php require __DIR__.'/inc/footer.php'; ?>
