<?php require_once __DIR__.'/../../includes/bootstrap.php';require_admin();$title=$title??'Admin';$ptype=(string)get('type','');$permMap=['products.php'=>'products','taxonomy.php'=>'content','orders.php'=>'orders','inventory.php'=>'inventory','coupons.php'=>'marketing','content.php'=>'content','reviews.php'=>'reviews','comments.php'=>'reviews','contacts.php'=>'contacts','media.php'=>'media','menus.php'=>'content','widgets.php'=>'content','shortcodes.php'=>'content','seo.php'=>'content','importer.php'=>'content','users.php'=>'settings','settings.php'=>'settings'];$required=$permMap[basename($_SERVER['PHP_SELF'])]??null;if($required&&!can_manage($required))redirect('/admin/index.php');$nav=[
['Dashboard','/admin/index.php','solar:widget-5-linear'],['Products','/admin/products.php','solar:box-linear'],['Categories & Tags','/admin/taxonomy.php','solar:layers-linear'],['Orders','/admin/orders.php','solar:bag-4-linear'],['Inventory','/admin/inventory.php','solar:box-minimalistic-linear'],['Coupons','/admin/coupons.php','solar:tag-linear'],
['Gadgets','/admin/content.php?type=gadgets','solar:smart-vacation-linear'],['Jersey','/admin/content.php?type=jersey','solar:shirt-linear'],['Fashion','/admin/content.php?type=fashion','solar:t-shirt-linear'],['Articles','/admin/content.php?type=articles','solar:document-text-linear'],['Docs','/admin/content.php?type=docs','solar:book-2-linear'],['Pages','/admin/content.php?type=pages','solar:notes-linear'],
['Engagement','/admin/engagement.php','solar:heart-linear'],['Reviews','/admin/reviews.php','solar:star-linear'],['Comments','/admin/comments.php','solar:chat-round-dots-linear'],['Contact Requests','/admin/contacts.php','solar:letter-linear'],['Media Library','/admin/media.php','solar:gallery-linear'],['Menus Builder','/admin/menus.php','solar:list-arrow-down-linear'],['Widgets','/admin/widgets.php','solar:widget-3-linear'],['Shortcodes','/admin/shortcodes.php','solar:code-square-linear'],['SEO / Schema / Speed','/admin/seo.php','solar:graph-up-linear'],['Sitemap Importer','/admin/importer.php','solar:database-import-linear'],['Users & Permissions','/admin/users.php','solar:users-group-rounded-linear'],['Settings','/admin/settings.php','solar:settings-linear']];?>
<!doctype html><html data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0f172a"><title><?=e($title)?> · PAROKO Admin</title><script src="https://cdn.tailwindcss.com"></script><script src="https://code.iconify.design/3/3.1.0/iconify.min.js"></script><script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script><style>:root{--paroko-font:'<?=e(setting('typography_font','Inter'))?>',Inter,ui-sans-serif,system-ui,sans-serif;--paroko-base:<?=e(setting('typography_base','16'))?>px;--paroko-radius:<?=e(setting('ui_radius','18'))?>px}body{font-family:var(--paroko-font);font-size:var(--paroko-base)}.rounded-xl{border-radius:calc(var(--paroko-radius) * .66)}.rounded-2xl{border-radius:var(--paroko-radius)}.rounded-\[28px\]{border-radius:calc(var(--paroko-radius) * 1.55)}.font-black{font-weight:<?=e(setting('typography_heading_weight','800'))?>}html[data-theme="dark"]{--bg:#070b0b;--surface:#0f1716;--surface-2:#131e1d;--text:#f8fafc;--muted:#9ca3af}html[data-theme="dark"] body{background:#070b0b;color:#f8fafc}html[data-theme="dark"] input,html[data-theme="dark"] select,html[data-theme="dark"] textarea{background:#131e1d!important;color:#f8fafc!important;border-color:rgba(255,255,255,.10)!important;padding:12px 14px!important}</style><style>[x-cloak]{display:none!important}body{font-family:Inter,ui-sans-serif,system-ui,sans-serif}.soft{box-shadow:0 18px 50px rgba(15,23,42,.08)}.shine{position:relative;overflow:hidden}75%,100%{transform:translateX(55%) rotate(12deg)}}.grad600{background:linear-gradient(135deg,#0f172a 0%,#2563eb 45%,#7c3aed 100%)}.grad600b{background:linear-gradient(135deg,#0b1220 0%,#0ea5e9 50%,#14b8a6 100%)}.cardgrad{background:linear-gradient(145deg,rgba(255,255,255,.98),rgba(248,250,252,.92))}.scrollbar-none::-webkit-scrollbar{display:none}.scrollbar-none{scrollbar-width:none},select,textarea{padding:12px 14px!important}</style></head><body class="bg-slate-50 text-slate-900" x-data="{open:false}">
<div class="min-h-screen lg:flex">
<aside :class="open?'translate-x-0':'-translate-x-full'" class="fixed inset-y-0 left-0 w-72 bg-gradient-to-b from-slate-950 via-slate-900 to-blue-950 text-white z-50 transform transition-transform duration-200 -translate-x-full lg:translate-x-0 lg:block">
 <div class="p-4 border-b border-white/10 flex items-center justify-between"><a href="/admin/index.php" class="font-black text-xl tracking-tight">PAROKO <span class="text-blue-300 text-xs">ADMIN</span></a><button class="lg:hidden p-2 rounded-xl hover:bg-white/10" @click="open=false"><span class="iconify" data-icon="solar:close-circle-linear"></span></button></div>
 <div class="p-3"><div class="shine grad600 rounded-2xl p-4"><div class="text-xs uppercase tracking-[.18em] text-white/70">Control Center</div><div class="font-black mt-1">Full-stack commerce</div><div class="text-xs text-white/70 mt-2">Content · Store · SEO · Growth</div></div></div>
 <nav class="px-3 pb-5 h-[calc(100vh-150px)] overflow-y-auto scrollbar-none space-y-1">
 <?php foreach($nav as $n): if((user()['role']??'')!=='admin'){ $u=parse_url($n[1],PHP_URL_PATH)?:''; $bn=basename($u); $pm=$permMap[$bn]??null; if($pm&&!can_manage($pm)) continue; } $active=(strpos($n[1],basename($_SERVER['PHP_SELF']))!==false && ($ptype==='' || strpos($n[1],'type='.$ptype)!==false)); ?><a href="<?=$n[1]?>" class="flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-semibold <?=($active?'bg-white text-slate-950 shadow-lg':'text-white/80 hover:bg-white/10 hover:text-white')?>"><span class="iconify text-lg" data-icon="<?=$n[2]?>"></span><span><?=$n[0]?></span></a><?php endforeach; ?>
 <div class="border-t border-white/10 my-3"></div><a href="/" target="_blank" class="flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-semibold text-white/80 hover:bg-white/10"><span class="iconify" data-icon="solar:globus-linear"></span>View Store</a><a href="/logout.php" class="flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-semibold text-white/80 hover:bg-white/10"><span class="iconify" data-icon="solar:logout-2-linear"></span>Logout</a>
 </nav>
</aside>
<div class="lg:ml-72 flex-1 min-w-0"><header class="sticky top-0 z-40 bg-white/90 backdrop-blur-xl border-b border-slate-200"><div class="px-4 sm:px-6 py-3 flex items-center gap-3"><button class="lg:hidden w-10 h-10 rounded-xl bg-slate-100" @click="open=true"><span class="iconify" data-icon="solar:hamburger-menu-linear"></span></button><div class="min-w-0"><div class="text-xs text-slate-400 uppercase tracking-[.18em]">PAROKO Admin</div><div class="font-black truncate"><?=e($title)?></div></div><div class="ml-auto flex items-center gap-2"><button id="adminThemeToggle" class="w-10 h-10 rounded-xl border border-slate-200 grid place-items-center"><span id="adminThemeIcon" class="iconify" data-icon="solar:moon-linear"></span></button><a href="/" target="_blank" class="hidden sm:flex px-3 py-2 rounded-xl border border-slate-200 text-sm font-bold">Storefront</a><div class="hidden sm:block text-sm text-slate-500"><?=e(user()['name'])?></div></div></div></header>
<main class="p-4 sm:p-6 max-w-[1500px] mx-auto">
<script>
document.getElementById('adminThemeToggle')?.addEventListener('click', function() {
  const html = document.documentElement;
  const isDark = html.getAttribute('data-theme') === 'dark';
  const newTheme = isDark ? 'light' : 'dark';
  html.setAttribute('data-theme', newTheme);
  localStorage.setItem('adminTheme', newTheme);
  const icon = document.getElementById('adminThemeIcon');
  icon.setAttribute('data-icon', newTheme === 'dark' ? 'solar:sun-linear' : 'solar:moon-linear');
});
const savedTheme = localStorage.getItem('adminTheme') || 'light';
document.documentElement.setAttribute('data-theme', savedTheme);
document.getElementById('adminThemeIcon').setAttribute('data-icon', savedTheme === 'dark' ? 'solar:sun-linear' : 'solar:moon-linear');
</script>
<?php if(is_post()): foreach(flashes() as $f): ?><div class="mb-4 rounded-2xl border px-4 py-3 text-sm <?=($f['type']==='success'?'bg-emerald-50 text-emerald-800 border-emerald-100':'bg-rose-50 text-rose-800 border-rose-100')?>"><?=e($f['message'])?></div><?php endforeach; else: foreach(flashes() as $f): ?><div class="mb-4 rounded-2xl border px-4 py-3 text-sm <?=($f['type']==='success'?'bg-emerald-50 text-emerald-800 border-emerald-100':'bg-rose-50 text-rose-800 border-rose-100')?>"><?=e($f['message'])?></div><?php endforeach; endif; ?>
