<?php require __DIR__.'/../includes/bootstrap.php';
if($_SERVER['REQUEST_METHOD']!=='POST')json_response(['ok'=>false,'message'=>'POST required'],405);
$data=json_decode(file_get_contents('php://input'),true) ?: [];
$action=$data['action']??'add';
if($action==='summary')json_response(['ok'=>true,'items'=>array_values(cart()),'count'=>cart_count(),'totals'=>cart_totals()]);
if($action==='clear'){$_SESSION['cart']=[];unset($_SESSION['coupon_discount']);json_response(['ok'=>true,'count'=>0,'totals'=>cart_totals()]);}
if($action==='remove'){ $key=(string)($data['key']??'');unset($_SESSION['cart'][$key]);json_response(['ok'=>true,'count'=>cart_count(),'items'=>array_values(cart()),'totals'=>cart_totals()]); }
if($action==='update'){ $key=(string)($data['key']??'');$qty=max(0,(int)($data['qty']??0));if(isset($_SESSION['cart'][$key])){if($qty===0)unset($_SESSION['cart'][$key]);else{$_SESSION['cart'][$key]['qty']=$qty;$_SESSION['cart'][$key]['line_total']=$_SESSION['cart'][$key]['price']*$qty+$_SESSION['cart'][$key]['printing_charge'];}}json_response(['ok'=>true,'count'=>cart_count(),'items'=>array_values(cart()),'totals'=>cart_totals()]); }
$productId=(int)($data['product_id']??0);$variantId=(int)($data['variant_id']??0);$qty=max(1,min(20,(int)($data['qty']??1)));$size=trim((string)($data['size']??''));$color=trim((string)($data['color']??''));$customName=trim((string)($data['custom_name']??''));$customNumber=trim((string)($data['custom_number']??''));
$st=db()->prepare('SELECT p.*,c.type category_type FROM products p JOIN categories c ON c.id=p.category_id WHERE p.id=? AND p.status=1');$st->execute([$productId]);$p=$st->fetch();if(!$p)json_response(['ok'=>false,'message'=>'Product not found'],404);
$variant=null;if($variantId){$vs=db()->prepare('SELECT * FROM variants WHERE id=? AND product_id=? AND status=1');$vs->execute([$variantId,$productId]);$variant=$vs->fetch();}else{$vs=db()->prepare('SELECT * FROM variants WHERE product_id=? AND status=1 ORDER BY id LIMIT 1');$vs->execute([$productId]);$variant=$vs->fetch();}
$price=(float)($variant['price']??$p['price']);$printing=($p['category_type']==='jersey' && $customName!=='' && $customNumber!=='')?(float)setting('printing_charge','150'):0;if($variant && (int)$variant['stock']<$qty)json_response(['ok'=>false,'message'=>'Not enough stock'],422);
$key=implode('|',[$productId,$variant['id']??0,$size,$color,$customName,$customNumber]);$existing=$_SESSION['cart'][$key]['qty']??0;$newQty=$existing+$qty;if($variant && (int)$variant['stock']<$newQty)json_response(['ok'=>false,'message'=>'Not enough stock for this quantity'],422);
$_SESSION['cart'][$key]=['key'=>$key,'product_id'=>$productId,'variant_id'=>$variant['id']??null,'name'=>$p['name'],'sku'=>$variant['sku']??$p['sku'],'image'=>$variant['image']??null,'size'=>$size?:($variant['size']??''),'color'=>$color?:($variant['color']??''),'custom_name'=>$customName,'custom_number'=>$customNumber,'printing_charge'=>$printing,'qty'=>$newQty,'price'=>$price,'line_total'=>$price*$newQty+$printing];json_response(['ok'=>true,'message'=>'Added to cart','count'=>cart_count(),'totals'=>cart_totals()]);
